// src/data/products.js
// Auto-generated consolidated product catalog
// Images reference /images/<filename> (public/images)

const products = [
  {
    name: "Urban Explorer Backpack",
    id: "backpack-1",
    category: "backpack",
    slug: "urban-explorer-backpack",
    price: null,
    priceDisplay: "$49.99",
    image: "/images/LumberUnion_UrbanExplorerBackpack_FrontLeft_Black_590x.webp",
    shortDesc: "Durable, water-resistant backpack perfect for travel and daily use.",
    longDesc: "",
    rating: 4.7,
    type: "backpack",
    color: "black",
    tags: ["travel", "daily", "water-resistant"]
  },
  {
    name: "Classic Campus Bag",
    id: "backpack-2",
    category: "backpack",
    slug: "classic-campus-bag",
    price: null,
    priceDisplay: "$39.99",
    image: "/images/000003_900x.webp",
    shortDesc: "Simple, lightweight campus bag for everyday carry.",
    longDesc: "",
    rating: 4.5,
    type: "backpack",
    color: "random",
    tags: ["campus", "lightweight"]
  },
  {
    name: "Adventure Pro Rucksack",
    id: "backpack-3",
    category: "backpack",
    slug: "adventure-pro-rucksack",
    price: null,
    priceDisplay: "$69.99",
    image: "/images/AdventurePro_Rucksack_1.webp",
    shortDesc: "Spacious, rugged design with extra compartments for long trips.",
    longDesc: "",
    rating: 4.6,
    type: "backpack",
    color: "random",
    tags: ["travel", "rugged"]
  },
  {
    name: "Apple iPhone 15",
    id: "electronics-1",
    category: "electronics",
    slug: "apple-iphone-15",
    price: null,
    priceDisplay: "₹79,999",
    image: "/images/IPhone_15_Pro_Max.webp",
    shortDesc: "128GB | A16 Bionic | Super Retina XDR Display",
    longDesc: "Experience next-level performance with the A16 ...ystem. Built for efficiency, speed, and photography perfection.",
    rating: 4.8,
    type: "smartphone",
    color: "random",
    tags: ["electronics", "mobile"]
  },
  {
    name: "Samsung Galaxy S24",
    id: "electronics-2",
    category: "electronics",
    slug: "samsung-galaxy-s24",
    price: null,
    priceDisplay: "₹69,999",
    image: "/images/gsmarena_001.webp",
    shortDesc: "Dynamic AMOLED | 5G | 256GB Storage",
    longDesc: "The Samsung Galaxy S24 redefines smartphone exp...lliant AMOLED display, and advanced AI-powered camera features.",
    rating: 4.7,
    type: "smartphone",
    color: "random",
    tags: ["electronics", "android"]
  },
  {
    name: "Sony WH-1000XM5 Headphones",
    id: "electronics-3",
    category: "electronics",
    slug: "sony-wh-1000xm5-headphones",
    price: null,
    priceDisplay: "₹29,999",
    image: "/images/ref-2803644-sony-hdphn-bnr_der-e8503034-a243-4c9a-ab76-f6d4feafc5ba.webp",
    shortDesc: "Industry-leading Noise Cancellation | 30hr Battery",
    longDesc: "Industry-leading noise cancellation with immersive sound and comfortable fit.",
    rating: 4.9,
    type: "headphones",
    color: "black",
    tags: ["noise-cancelling", "audio"]
  },
  {
    name: "MacBook Air M3",
    id: "electronics-4",
    category: "electronics",
    slug: "macbook-air-m3",
    price: null,
    priceDisplay: "₹1,14,999",
    image: "/images/m3-twoscreens-6c.webp",
    shortDesc: "13-inch Retina | 8GB RAM | 256GB SSD",
    longDesc: "The MacBook Air M3 delivers ultra-fast performance, a vivid Retina display, and sleek portability — perfect for work, creativity, and travel.",
    rating: 4.6,
    type: "laptop",
    color: "random",
    tags: ["electronics", "apple"]
  },
  {
    name: "Wireless Charger Pad",
    id: "electronics-5",
    category: "electronics",
    slug: "wireless-charger-pad",
    price: null,
    priceDisplay: "₹999",
    image: "/images/wireless-charger-pad.webp",
    shortDesc: "Fast wireless charging pad for Qi devices",
    longDesc: "Compact charger with fast-charge support and non-slip surface.",
    rating: 4.1,
    type: "charger",
    color: "random",
    tags: ["wireless", "accessory"]
  },
  {
    name: "New Balance 574",
    id: "lifestyle-1",
    category: "lifestyle",
    slug: "new-balance-574",
    price: 9999,
    priceDisplay: "₹9,999",
    image: "/images/NEW+BALANCE+574+2024+RELEASE+BLACK+GRAY+AND+WHITE.webp",
    shortDesc: "Classic comfort sneakers",
    longDesc: "Legendary New Balance 574 redesigned with modern comfort.",
    rating: 4.6,
    type: "shoes",
    color: "black",
    tags: ["sneakers", "casual"]
  },
  {
    name: "Cotton Crew Tee Pack",
    id: "lifestyle-2",
    category: "lifestyle",
    slug: "cotton-crew-tee-pack",
    price: null,
    priceDisplay: "₹899",
    image: "/images/cotton-tee-pack.webp",
    shortDesc: "3-pack cotton tees",
    longDesc: "Soft breathable tees for daily wear.",
    rating: 4.0,
    type: "shirt",
    color: "random",
    tags: ["cotton", "casual"]
  },
  {
    name: "Sport Runner Sneakers",
    id: "sneakers-1",
    category: "sneakers",
    slug: "sport-runner-sneakers",
    price: null,
    priceDisplay: "₹2,999",
    image: "/images/sport-runner-900x.webp",
    shortDesc: "Lightweight running shoes",
    longDesc: "Cushioned midsoles for better shock absorption on runs.",
    rating: 4.2,
    type: "shoes",
    color: "random",
    tags: ["running", "sports"]
  },
  {
    name: "Lifestyle Denim Jacket",
    id: "lifestyle-3",
    category: "lifestyle",
    slug: "lifestyle-denim-jacket",
    price: null,
    priceDisplay: "₹2,499",
    image: "/images/denim-jacket.webp",
    shortDesc: "Classic denim jacket",
    longDesc: "Timeless denim jacket with durable stitching and soft lining.",
    rating: 4.4,
    type: "jacket",
    color: "blue",
    tags: ["denim", "casual"]
  },
  {
    name: "Designer Sunglasses UV400",
    id: "lifestyle-5",
    category: "lifestyle",
    slug: "designer-sunglasses-uv400",
    price: null,
    priceDisplay: "₹2,999",
    image: "/images/designer-sunglasses.webp",
    shortDesc: "UV400 protection with polarized lenses",
    longDesc: "Stylish sunglasses with polarization for clearer vision.",
    rating: 4.5,
    type: "sunglasses",
    color: "random",
    tags: ["accessory", "fashion"]
  },
  {
    name: "Premium Leather Wallet",
    id: "lifestyle-6",
    category: "lifestyle",
    slug: "premium-leather-wallet",
    price: null,
    priceDisplay: "₹1,499",
    image: "/images/leather-wallet.webp",
    shortDesc: "Slim leather wallet with RFID protection",
    longDesc: "Classic wallet constructed with premium leather.",
    rating: 4.4,
    type: "wallet",
    color: "brown",
    tags: ["leather", "accessory"]
  },
  {
  name: "Nomad Travel Backpack",
  id: "backpack-4",
  category: "backpack",
  slug: "nomad-travel-backpack",
  price: null,
  priceDisplay: "$59.99",
  image: "https://images.unsplash.com/photo-1514474959185-1472d4c4e3a1",
  shortDesc: "Expandable backpack designed for long journeys.",
  longDesc: "A durable travel backpack with padded laptop sleeve, expandable storage, and ergonomic straps for long trips.",
  rating: 4.6,
  type: "backpack",
  color: "grey",
  tags: ["travel", "expandable"]
},
{
  name: "Minimal Office Backpack",
  id: "backpack-5",
  category: "backpack",
  slug: "minimal-office-backpack",
  price: null,
  priceDisplay: "$44.99",
  image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa",
  shortDesc: "Sleek backpack for office and tech carry.",
  longDesc: "Designed for professionals, featuring a slim profile, laptop padding, and water-resistant fabric.",
  rating: 4.4,
  type: "backpack",
  color: "black",
  tags: ["office", "minimal"]
},
{
  name: "Mountain Trek Backpack",
  id: "backpack-6",
  category: "backpack",
  slug: "mountain-trek-backpack",
  price: null,
  priceDisplay: "$79.99",
  image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee",
  shortDesc: "Heavy-duty trekking backpack.",
  longDesc: "Built for hikers with reinforced zippers, rain cover, and large capacity compartments.",
  rating: 4.8,
  type: "backpack",
  color: "green",
  tags: ["trekking", "outdoor"]
},
{
  name: "Daily Essentials Backpack",
  id: "backpack-7",
  category: "backpack",
  slug: "daily-essentials-backpack",
  price: null,
  priceDisplay: "$34.99",
  image: "https://images.unsplash.com/photo-1491637639811-60e2756cc1c7",
  shortDesc: "Compact everyday backpack.",
  longDesc: "Lightweight backpack for daily commute with smart internal organization.",
  rating: 4.2,
  type: "backpack",
  color: "blue",
  tags: ["daily", "compact"]
},
{
  name: "Anti-Theft Smart Backpack",
  id: "backpack-8",
  category: "backpack",
  slug: "anti-theft-smart-backpack",
  price: null,
  priceDisplay: "$89.99",
  image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62",
  shortDesc: "Smart backpack with hidden zippers.",
  longDesc: "Anti-theft design with USB charging port and reinforced compartments.",
  rating: 4.7,
  type: "backpack",
  color: "black",
  tags: ["smart", "secure"]
},
{
  name: "Canvas Vintage Backpack",
  id: "backpack-9",
  category: "backpack",
  slug: "canvas-vintage-backpack",
  price: null,
  priceDisplay: "$54.99",
  image: "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f",
  shortDesc: "Vintage-style canvas backpack.",
  longDesc: "Classic canvas build with leather accents for a timeless look.",
  rating: 4.3,
  type: "backpack",
  color: "brown",
  tags: ["vintage", "canvas"]
},
{
  name: "Gym & Work Hybrid Backpack",
  id: "backpack-10",
  category: "backpack",
  slug: "gym-work-hybrid-backpack",
  price: null,
  priceDisplay: "$64.99",
  image: "https://images.unsplash.com/photo-1585386959984-a4155228f7c9",
  shortDesc: "Dual-purpose gym and office backpack.",
  longDesc: "Separate compartments for shoes, clothes, and electronics.",
  rating: 4.5,
  type: "backpack",
  color: "black",
  tags: ["gym", "office"]
},
{
  name: "Apple Watch Series 9",
  id: "electronics-6",
  category: "electronics",
  slug: "apple-watch-series-9",
  price: null,
  priceDisplay: "₹41,999",
  image: "https://images.unsplash.com/photo-1516574187841-cb9cc2ca948b",
  shortDesc: "Advanced health tracking smartwatch.",
  longDesc: "Features ECG, blood oxygen tracking, and seamless iPhone integration.",
  rating: 4.7,
  type: "smartwatch",
  color: "random",
  tags: ["apple", "wearable"]
},
{
  name: "Dell XPS 13",
  id: "electronics-7",
  category: "electronics",
  slug: "dell-xps-13",
  price: null,
  priceDisplay: "₹1,29,999",
  image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8",
  shortDesc: "Ultra-thin premium laptop.",
  longDesc: "Compact laptop with InfinityEdge display and high performance.",
  rating: 4.6,
  type: "laptop",
  color: "silver",
  tags: ["windows", "laptop"]
},
{
  name: "GoPro Hero 12",
  id: "electronics-8",
  category: "electronics",
  slug: "gopro-hero-12",
  price: null,
  priceDisplay: "₹39,999",
  image: "https://images.unsplash.com/photo-1519183071298-a2962be96c6f",
  shortDesc: "Action camera for adventure lovers.",
  longDesc: "Waterproof 5K video recording with advanced stabilization.",
  rating: 4.5,
  type: "camera",
  color: "black",
  tags: ["camera", "action"]
},
{
  name: "Bluetooth Soundbar",
  id: "electronics-9",
  category: "electronics",
  slug: "bluetooth-soundbar",
  price: null,
  priceDisplay: "₹14,999",
  image: "https://images.unsplash.com/photo-1587574293340-e0011c4e8ec8",
  shortDesc: "High bass home soundbar.",
  longDesc: "Powerful sound output with Bluetooth and HDMI support.",
  rating: 4.3,
  type: "audio",
  color: "black",
  tags: ["home-audio", "sound"]
},
{
  name: "Mechanical Gaming Keyboard",
  id: "electronics-10",
  category: "electronics",
  slug: "mechanical-gaming-keyboard",
  price: null,
  priceDisplay: "₹6,499",
  image: "https://images.unsplash.com/photo-1611078489935-0cb964de46f5",
  shortDesc: "RGB mechanical keyboard.",
  longDesc: "Tactile switches with customizable RGB lighting.",
  rating: 4.4,
  type: "keyboard",
  color: "black",
  tags: ["gaming", "accessory"]
},
{
  name: "Nike Air Max 90",
  id: "sneakers-2",
  category: "sneakers",
  slug: "nike-air-max-90",
  price: null,
  priceDisplay: "₹11,999",
  image: "https://images.unsplash.com/photo-1606813902914-8e34c1c3c2d6",
  shortDesc: "Iconic Air Max cushioning.",
  longDesc: "Classic sneaker with visible air cushioning and premium materials.",
  rating: 4.6,
  type: "shoes",
  color: "white",
  tags: ["nike", "streetwear"]
},
{
  name: "Adidas Ultraboost",
  id: "sneakers-3",
  category: "sneakers",
  slug: "adidas-ultraboost",
  price: null,
  priceDisplay: "₹14,999",
  image: "https://images.unsplash.com/photo-1600180758890-6c1d5c34c5e4",
  shortDesc: "High-performance running sneakers.",
  longDesc: "Boost midsole for energy return and comfort.",
  rating: 4.8,
  type: "shoes",
  color: "black",
  tags: ["running", "adidas"]
},
{
  name: "Puma RS-X",
  id: "sneakers-4",
  category: "sneakers",
  slug: "puma-rsx",
  price: null,
  priceDisplay: "₹9,499",
  image: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77",
  shortDesc: "Bold retro sneakers.",
  longDesc: "Chunky silhouette inspired by retro running shoes.",
  rating: 4.3,
  type: "shoes",
  color: "random",
  tags: ["retro", "puma"]
},
{
  name: "Premium Analog Wrist Watch",
  id: "lifestyle-7",
  category: "lifestyle",
  slug: "premium-analog-wrist-watch",
  price: null,
  priceDisplay: "₹4,999",
  image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30",
  shortDesc: "Elegant analog watch with leather strap",
  longDesc: "A premium analog wrist watch featuring a stainless steel dial and genuine leather strap, suitable for both formal and casual wear.",
  rating: 4.5,
  type: "watch",
  color: "brown",
  tags: ["watch", "fashion", "accessory"]
},
{
  name: "Casual Canvas Belt",
  id: "lifestyle-8",
  category: "lifestyle",
  slug: "casual-canvas-belt",
  price: null,
  priceDisplay: "₹799",
  image: "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519",
  shortDesc: "Durable canvas belt for daily wear",
  longDesc: "Strong and flexible canvas belt designed for everyday comfort with an adjustable metal buckle.",
  rating: 4.1,
  type: "belt",
  color: "black",
  tags: ["belt", "casual", "accessory"]
},
{
  name: "Winter Knit Beanie",
  id: "lifestyle-9",
  category: "lifestyle",
  slug: "winter-knit-beanie",
  price: null,
  priceDisplay: "₹599",
  image: "https://images.unsplash.com/photo-1542060748-10c28b62716f",
  shortDesc: "Warm knitted beanie cap",
  longDesc: "Soft and stretchable knit beanie that provides warmth and comfort during winter seasons.",
  rating: 4.3,
  type: "cap",
  color: "grey",
  tags: ["winter", "fashion"]
},
{
  name: "Reusable Stainless Steel Water Bottle",
  id: "lifestyle-10",
  category: "lifestyle",
  slug: "reusable-steel-water-bottle",
  price: null,
  priceDisplay: "₹1,199",
  image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8",
  shortDesc: "Eco-friendly insulated water bottle",
  longDesc: "Double-wall insulated stainless steel bottle that keeps drinks cold or hot for hours, perfect for gym, travel, and office use.",
  rating: 4.6,
  type: "bottle",
  color: "silver",
  tags: ["eco-friendly", "daily-use"]
},
{
  name: "Organic Basmati Rice 5kg",
  id: "grocery-1",
  category: "grocery",
  slug: "organic-basmati-rice",
  price: null,
  priceDisplay: "₹749",
  image: "https://images.unsplash.com/photo-1604908177225-1c3f7bfa4f9b",
  shortDesc: "Premium long-grain basmati rice",
  longDesc: "Naturally aged organic basmati rice with rich aroma and long grains.",
  rating: 4.6,
  type: "grains",
  color: "white",
  tags: ["organic", "daily-use"]
},
{
  name: "Cold Pressed Sunflower Oil 1L",
  id: "grocery-2",
  category: "grocery",
  slug: "sunflower-oil",
  price: null,
  priceDisplay: "₹299",
  image: "https://images.unsplash.com/photo-1627485937980-221c88ac04c1",
  shortDesc: "Healthy cooking oil",
  longDesc: "Cold pressed sunflower oil rich in Vitamin E.",
  rating: 4.4,
  type: "oil",
  color: "yellow",
  tags: ["healthy", "cooking"]
},
{
  name: "Whole Wheat Atta 10kg",
  id: "grocery-3",
  category: "grocery",
  slug: "whole-wheat-atta",
  price: null,
  priceDisplay: "₹499",
  image: "https://images.unsplash.com/photo-1627485937316-45b9e25f7d7a",
  shortDesc: "Stone-ground wheat flour",
  longDesc: "High-fiber whole wheat atta for soft and nutritious rotis.",
  rating: 4.5,
  type: "flour",
  color: "brown",
  tags: ["wheat", "staple"]
},
{
  name: "Raw Almonds 500g",
  id: "grocery-4",
  category: "grocery",
  slug: "raw-almonds",
  price: null,
  priceDisplay: "₹699",
  image: "https://images.unsplash.com/photo-1508747703725-719777637510",
  shortDesc: "Premium quality almonds",
  longDesc: "Crunchy raw almonds packed with protein and nutrients.",
  rating: 4.7,
  type: "dry-fruits",
  color: "brown",
  tags: ["nuts", "protein"]
},
{
  name: "Organic Honey 500g",
  id: "grocery-5",
  category: "grocery",
  slug: "organic-honey",
  price: null,
  priceDisplay: "₹399",
  image: "https://images.unsplash.com/photo-1587049352851-8d7e0c8b7e0b",
  shortDesc: "Pure natural honey",
  longDesc: "Unprocessed organic honey with natural sweetness.",
  rating: 4.6,
  type: "sweetener",
  color: "amber",
  tags: ["organic", "natural"]
},
{
  name: "Instant Coffee Powder 200g",
  id: "grocery-6",
  category: "grocery",
  slug: "instant-coffee",
  price: null,
  priceDisplay: "₹349",
  image: "https://images.unsplash.com/photo-1509042239860-f550ce710b93",
  shortDesc: "Strong aroma instant coffee",
  longDesc: "Rich-flavored instant coffee for quick energy boosts.",
  rating: 4.3,
  type: "beverage",
  color: "dark-brown",
  tags: ["coffee", "beverage"]
},
{
  name: "Digital Thermometer",
  id: "healthcare-1",
  category: "healthcare",
  slug: "digital-thermometer",
  price: null,
  priceDisplay: "₹299",
  image: "https://images.unsplash.com/photo-1580281657527-47a5f6c8c0f4",
  shortDesc: "Fast and accurate temperature readings",
  longDesc: "Easy-to-use digital thermometer with quick response time.",
  rating: 4.4,
  type: "medical-device",
  color: "white",
  tags: ["medical", "essential"]
},
{
  name: "Blood Pressure Monitor",
  id: "healthcare-2",
  category: "healthcare",
  slug: "bp-monitor",
  price: null,
  priceDisplay: "₹1,999",
  image: "https://images.unsplash.com/photo-1580281658619-0fbd7b8c7c59",
  shortDesc: "Automatic BP monitoring device",
  longDesc: "Clinically accurate digital blood pressure monitor.",
  rating: 4.6,
  type: "medical-device",
  color: "grey",
  tags: ["health", "monitor"]
},
{
  name: "Vitamin C Tablets",
  id: "healthcare-3",
  category: "healthcare",
  slug: "vitamin-c-tablets",
  price: null,
  priceDisplay: "₹249",
  image: "https://images.unsplash.com/photo-1584305574647-0c1f8a8a58c1",
  shortDesc: "Immunity booster tablets",
  longDesc: "Vitamin C supplements to support immune health.",
  rating: 4.5,
  type: "supplement",
  color: "orange",
  tags: ["vitamins", "immunity"]
},
{
  name: "First Aid Kit",
  id: "healthcare-4",
  category: "healthcare",
  slug: "first-aid-kit",
  price: null,
  priceDisplay: "₹599",
  image: "https://images.unsplash.com/photo-1603398938378-e54fa55d0c92",
  shortDesc: "Complete emergency first aid kit",
  longDesc: "Includes bandages, antiseptic, scissors, and essential supplies.",
  rating: 4.7,
  type: "emergency",
  color: "red",
  tags: ["emergency", "safety"]
},
{
  name: "Hand Sanitizer 500ml",
  id: "healthcare-5",
  category: "healthcare",
  slug: "hand-sanitizer",
  price: null,
  priceDisplay: "₹199",
  image: "https://images.unsplash.com/photo-1583947582886-fb07c5d4c08d",
  shortDesc: "Kills 99.9% germs",
  longDesc: "Alcohol-based hand sanitizer for daily hygiene.",
  rating: 4.2,
  type: "hygiene",
  color: "clear",
  tags: ["sanitizer", "hygiene"]
},
{
  name: "Pulse Oximeter",
  id: "healthcare-6",
  category: "healthcare",
  slug: "pulse-oximeter",
  price: null,
  priceDisplay: "₹1,299",
  image: "https://images.unsplash.com/photo-1600959907703-125ba1374a12",
  shortDesc: "Measures oxygen saturation",
  longDesc: "Accurate SpO2 and pulse rate monitoring device.",
  rating: 4.6,
  type: "medical-device",
  color: "black",
  tags: ["oxygen", "health"]
},
{
  name: "Apple Watch SE (2nd Gen)",
  id: "smartwatch-1",
  category: "smartwatch",
  slug: "apple-watch-se",
  price: null,
  priceDisplay: "₹29,999",
  image: "https://images.unsplash.com/photo-1516574187841-cb9cc2ca948b",
  shortDesc: "Fitness and health tracking",
  longDesc: "Advanced fitness tracking with heart rate and activity monitoring.",
  rating: 4.7,
  type: "wearable",
  color: "silver",
  tags: ["apple", "fitness"]
},
{
  name: "Samsung Galaxy Watch 6",
  id: "smartwatch-2",
  category: "smartwatch",
  slug: "galaxy-watch-6",
  price: null,
  priceDisplay: "₹34,999",
  image: "https://images.unsplash.com/photo-1617043786394-f977fa12eddf",
  shortDesc: "Smart health insights",
  longDesc: "Tracks sleep, workouts, and heart health.",
  rating: 4.6,
  type: "wearable",
  color: "black",
  tags: ["samsung", "android"]
},
{
  name: "Noise ColorFit Pro 4",
  id: "smartwatch-3",
  category: "smartwatch",
  slug: "noise-colorfit-pro-4",
  price: null,
  priceDisplay: "₹3,999",
  image: "https://images.unsplash.com/photo-1629429407879-b2f0f8d4d9e1",
  shortDesc: "Budget fitness smartwatch",
  longDesc: "Affordable smartwatch with AMOLED display.",
  rating: 4.4,
  type: "wearable",
  color: "blue",
  tags: ["budget", "fitness"]
},
{
  name: "Boat Wave Call",
  id: "smartwatch-4",
  category: "smartwatch",
  slug: "boat-wave-call",
  price: null,
  priceDisplay: "₹2,999",
  image: "https://images.unsplash.com/photo-1603791440384-56cd371ee9a7",
  shortDesc: "Bluetooth calling smartwatch",
  longDesc: "Smartwatch with Bluetooth calling and voice assistant.",
  rating: 4.2,
  type: "wearable",
  color: "black",
  tags: ["calling", "boat"]
},
{
  name: "Fitbit Versa 4",
  id: "smartwatch-5",
  category: "smartwatch",
  slug: "fitbit-versa-4",
  price: null,
  priceDisplay: "₹22,999",
  image: "https://images.unsplash.com/photo-1557821552-17105176677c",
  shortDesc: "Advanced fitness smartwatch",
  longDesc: "Tracks heart health, sleep stages, and workouts.",
  rating: 4.5,
  type: "wearable",
  color: "black",
  tags: ["fitbit", "health"]
},
{
  name: "Amazfit GTR 4",
  id: "smartwatch-6",
  category: "smartwatch",
  slug: "amazfit-gtr-4",
  price: null,
  priceDisplay: "₹16,999",
  image: "https://images.unsplash.com/photo-1617043786029-07b3a6e6d7c7",
  shortDesc: "Long battery life smartwatch",
  longDesc: "Up to 14-day battery with advanced fitness tracking.",
  rating: 4.6,
  type: "wearable",
  color: "grey",
  tags: ["battery", "fitness"]
},
{
  name: "Apple AirPods Pro (2nd Gen)",
  id: "headphones-1",
  category: "wireless-headphones",
  slug: "airpods-pro-2",
  price: null,
  priceDisplay: "₹24,999",
  image: "https://images.unsplash.com/photo-1600294037681-c80b4cb5b434",
  shortDesc: "Active noise cancellation earbuds",
  longDesc: "Premium sound with adaptive transparency and ANC.",
  rating: 4.8,
  type: "earbuds",
  color: "white",
  tags: ["apple", "anc"]
},
{
  name: "Sony WF-1000XM5",
  id: "headphones-2",
  category: "wireless-headphones",
  slug: "sony-wf-1000xm5",
  price: null,
  priceDisplay: "₹22,999",
  image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df",
  shortDesc: "Industry-leading ANC earbuds",
  longDesc: "Exceptional noise cancellation with immersive sound.",
  rating: 4.7,
  type: "earbuds",
  color: "black",
  tags: ["sony", "premium"]
},
{
  name: "Boat Airdopes 141",
  id: "headphones-3",
  category: "wireless-headphones",
  slug: "boat-airdopes-141",
  price: null,
  priceDisplay: "₹1,499",
  image: "https://images.unsplash.com/photo-1599669454699-248893623440",
  shortDesc: "Budget true wireless earbuds",
  longDesc: "Affordable earbuds with long battery life.",
  rating: 4.2,
  type: "earbuds",
  color: "black",
  tags: ["budget", "boat"]
},
{
  name: "JBL Tune 230NC",
  id: "headphones-4",
  category: "wireless-headphones",
  slug: "jbl-tune-230nc",
  price: null,
  priceDisplay: "₹5,999",
  image: "https://images.unsplash.com/photo-1629429408443-1f27c3c9a0e8",
  shortDesc: "Pure bass wireless earbuds",
  longDesc: "JBL signature sound with noise cancellation.",
  rating: 4.4,
  type: "earbuds",
  color: "white",
  tags: ["jbl", "music"]
},
{
  name: "Samsung Galaxy Buds 2 Pro",
  id: "headphones-5",
  category: "wireless-headphones",
  slug: "galaxy-buds-2-pro",
  price: null,
  priceDisplay: "₹18,999",
  image: "https://images.unsplash.com/photo-1617043786223-4c8f0c1e4f4b",
  shortDesc: "Premium Samsung earbuds",
  longDesc: "360 audio with intelligent ANC.",
  rating: 4.6,
  type: "earbuds",
  color: "violet",
  tags: ["samsung", "anc"]
},
{
  name: "Nothing Ear (2)",
  id: "headphones-6",
  category: "wireless-headphones",
  slug: "nothing-ear-2",
  price: null,
  priceDisplay: "₹9,999",
  image: "https://images.unsplash.com/photo-1629429408583-9d7e2a1f3b2f",
  shortDesc: "Transparent design earbuds",
  longDesc: "Unique transparent design with clear sound.",
  rating: 4.5,
  type: "earbuds",
  color: "transparent",
  tags: ["design", "nothing"]
}








];


export default products;
