// src/data/products.js
// Auto-generated consolidated product catalog
// Images reference /images/<filename> (public/images)

const products = [
  {
    name: "Urban Explorer Backpack",
    id: "backpack-1",
    category: "backpack",
    slug: "urban-explorer-backpack",
    price: null,
    priceDisplay: "$49.99",
    image: "/images/LumberUnion_UrbanExplorerBackpack_FrontLeft_Black_590x.webp",
    shortDesc: "Durable, water-resistant backpack perfect for travel and daily use.",
    longDesc: "",
    rating: 4.7,
    type: "backpack",
    color: "black",
    tags: ["travel", "daily", "water-resistant"]
  },
  {
    name: "Classic Campus Bag",
    id: "backpack-2",
    category: "backpack",
    slug: "classic-campus-bag",
    price: null,
    priceDisplay: "$39.99",
    image: "/images/000003_900x.webp",
    shortDesc: "Simple, lightweight campus bag for everyday carry.",
    longDesc: "",
    rating: 4.5,
    type: "backpack",
    color: "random",
    tags: ["campus", "lightweight"]
  },
  {
    name: "Adventure Pro Rucksack",
    id: "backpack-3",
    category: "backpack",
    slug: "adventure-pro-rucksack",
    price: null,
    priceDisplay: "$69.99",
    image: "/images/AdventurePro_Rucksack_1.webp",
    shortDesc: "Spacious, rugged design with extra compartments for long trips.",
    longDesc: "",
    rating: 4.6,
    type: "backpack",
    color: "random",
    tags: ["travel", "rugged"]
  },
  {
    name: "Apple iPhone 15",
    id: "electronics-1",
    category: "electronics",
    slug: "apple-iphone-15",
    price: null,
    priceDisplay: "₹79,999",
    image: "/images/IPhone_15_Pro_Max.webp",
    shortDesc: "128GB | A16 Bionic | Super Retina XDR Display",
    longDesc: "Experience next-level performance with the A16 ...ystem. Built for efficiency, speed, and photography perfection.",
    rating: 4.8,
    type: "smartphone",
    color: "random",
    tags: ["electronics", "mobile"]
  },
  {
    name: "Samsung Galaxy S24",
    id: "electronics-2",
    category: "electronics",
    slug: "samsung-galaxy-s24",
    price: null,
    priceDisplay: "₹69,999",
    image: "/images/gsmarena_001.webp",
    shortDesc: "Dynamic AMOLED | 5G | 256GB Storage",
    longDesc: "The Samsung Galaxy S24 redefines smartphone exp...lliant AMOLED display, and advanced AI-powered camera features.",
    rating: 4.7,
    type: "smartphone",
    color: "random",
    tags: ["electronics", "android"]
  },
  {
    name: "Sony WH-1000XM5 Headphones",
    id: "electronics-3",
    category: "electronics",
    slug: "sony-wh-1000xm5-headphones",
    price: null,
    priceDisplay: "₹29,999",
    image: "/images/ref-2803644-sony-hdphn-bnr_der-e8503034-a243-4c9a-ab76-f6d4feafc5ba.webp",
    shortDesc: "Industry-leading Noise Cancellation | 30hr Battery",
    longDesc: "Industry-leading noise cancellation with immersive sound and comfortable fit.",
    rating: 4.9,
    type: "headphones",
    color: "black",
    tags: ["noise-cancelling", "audio"]
  },
  {
    name: "MacBook Air M3",
    id: "electronics-4",
    category: "electronics",
    slug: "macbook-air-m3",
    price: null,
    priceDisplay: "₹1,14,999",
    image: "/images/m3-twoscreens-6c.webp",
    shortDesc: "13-inch Retina | 8GB RAM | 256GB SSD",
    longDesc: "The MacBook Air M3 delivers ultra-fast performance, a vivid Retina display, and sleek portability — perfect for work, creativity, and travel.",
    rating: 4.6,
    type: "laptop",
    color: "random",
    tags: ["electronics", "apple"]
  },
  {
    name: "Wireless Charger Pad",
    id: "electronics-5",
    category: "electronics",
    slug: "wireless-charger-pad",
    price: null,
    priceDisplay: "₹999",
    image: "/images/wireless-charger-pad.webp",
    shortDesc: "Fast wireless charging pad for Qi devices",
    longDesc: "Compact charger with fast-charge support and non-slip surface.",
    rating: 4.1,
    type: "charger",
    color: "random",
    tags: ["wireless", "accessory"]
  },
  {
    name: "New Balance 574",
    id: "lifestyle-1",
    category: "lifestyle",
    slug: "new-balance-574",
    price: 9999,
    priceDisplay: "₹9,999",
    image: "/images/NEW+BALANCE+574+2024+RELEASE+BLACK+GRAY+AND+WHITE.webp",
    shortDesc: "Classic comfort sneakers",
    longDesc: "Legendary New Balance 574 redesigned with modern comfort.",
    rating: 4.6,
    type: "shoes",
    color: "black",
    tags: ["sneakers", "casual"]
  },
  {
    name: "Cotton Crew Tee Pack",
    id: "lifestyle-2",
    category: "lifestyle",
    slug: "cotton-crew-tee-pack",
    price: null,
    priceDisplay: "₹899",
    image: "/images/cotton-tee-pack.webp",
    shortDesc: "3-pack cotton tees",
    longDesc: "Soft breathable tees for daily wear.",
    rating: 4.0,
    type: "shirt",
    color: "random",
    tags: ["cotton", "casual"]
  },
  {
    name: "Sport Runner Sneakers",
    id: "sneakers-1",
    category: "sneakers",
    slug: "sport-runner-sneakers",
    price: null,
    priceDisplay: "₹2,999",
    image: "/images/sport-runner-900x.webp",
    shortDesc: "Lightweight running shoes",
    longDesc: "Cushioned midsoles for better shock absorption on runs.",
    rating: 4.2,
    type: "shoes",
    color: "random",
    tags: ["running", "sports"]
  },
  {
    name: "Lifestyle Denim Jacket",
    id: "lifestyle-3",
    category: "lifestyle",
    slug: "lifestyle-denim-jacket",
    price: null,
    priceDisplay: "₹2,499",
    image: "/images/denim-jacket.webp",
    shortDesc: "Classic denim jacket",
    longDesc: "Timeless denim jacket with durable stitching and soft lining.",
    rating: 4.4,
    type: "jacket",
    color: "blue",
    tags: ["denim", "casual"]
  },
  {
    name: "Designer Sunglasses UV400",
    id: "lifestyle-5",
    category: "lifestyle",
    slug: "designer-sunglasses-uv400",
    price: null,
    priceDisplay: "₹2,999",
    image: "/images/designer-sunglasses.webp",
    shortDesc: "UV400 protection with polarized lenses",
    longDesc: "Stylish sunglasses with polarization for clearer vision.",
    rating: 4.5,
    type: "sunglasses",
    color: "random",
    tags: ["accessory", "fashion"]
  },
  {
    name: "Premium Leather Wallet",
    id: "lifestyle-6",
    category: "lifestyle",
    slug: "premium-leather-wallet",
    price: null,
    priceDisplay: "₹1,499",
    image: "/images/leather-wallet.webp",
    shortDesc: "Slim leather wallet with RFID protection",
    longDesc: "Classic wallet constructed with premium leather.",
    rating: 4.4,
    type: "wallet",
    color: "brown",
    tags: ["leather", "accessory"]
  }
];


export default products;
